name: CI/CD

on:
  push:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          docker run --rm \
          -v ${{github.workspace}}:/src \
          -w /src/build \
          -u $(id -u):$(id -g) \
          emscripten/emsdk:latest \
          $SHELL -c "emcmake cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build ."

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{github.workspace}}/build
        run: |
          tar zcf ${{github.event.repository.name}}.tar.gz application.js application.wasm
          
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/${{github.event.repository.name}}.tar.gz
          token: ${{secrets.ACTION_RELEASE_TOKEN}}
          generate_release_notes: true
          make_latest: true

      - name: GitHubAssistantBot Preprocess
        id: preprocess_commits
        if: success() || failure()
        run: |
          commits_json=$(cat <<EOL
          ${{toJson(github.event.commits)}}
          EOL
          )

          echo "commits=$(echo "$commits_json" | jq -c '[.[] | {message: .message, url: .url}]' || echo "[]")" >> $GITHUB_OUTPUT

      - name: GitHubAssistantBot
        if: success() || failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://node-red.geeken.me/github_assistant_bot'
          data: |
            {
              "key": "${{secrets.ASSISTANT_BOT_KEY}}",
              "actor": "${{github.actor}}",
              "platform": "${{matrix.board_target}}",
              "changes": "https://github.com/${{github.repository}}/commit/${{github.sha}}",
              "commits": ${{steps.preprocess_commits.outputs.commits}},
              "event": "${{github.event_name}}",
              "reference": "${{github.ref_name}}",
              "report": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
              "repository": "${{github.repository}}",
              "status": "${{job.status}}"
            }
